name: Bridge Indexer

on:
  push:
    paths: "apps/indexer/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run test
        run: cargo test
        working-directory: apps/indexer
      - name: Lowercase repository
        run: |
          echo "LOWERCASE_REPOSITORY=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: apps/indexer
          tags: ghcr.io/${{ env.LOWERCASE_REPOSITORY }}:latest
          build-args: |
            "GIT_HASH=$GITHUB_SHA"